import { MateriaPrima, Fermentacion, ProductoStock, PCC, Incidencia, HojaProduccion, HojaEnvasado } from "./types";

export const DEMO_MATERIAS_PRIMAS: MateriaPrima[] = [
  {
    id: "MP001",
    nombre: "Extracto de cardo mariano",
    lote: "LOT-CM-2026-001",
    proveedor: "Herbal Iberia S.L.",
    fechaCaducidad: "2027-03-15",
    fechaRecepcion: "2026-03-01",
    cantidad: 5,
    unidad: "kg",
    coaPendiente: false,
    notas: "",
    fotos: [],
  },
  {
    id: "MP002",
    nombre: "Vitamina C (acido ascorbico)",
    lote: "LOT-VC-2026-045",
    proveedor: "NutriChem Europe",
    fechaCaducidad: "2026-06-20",
    fechaRecepcion: "2026-02-15",
    cantidad: 2,
    unidad: "kg",
    coaPendiente: true,
    notas: "Pendiente COA del proveedor",
    fotos: [],
  },
  {
    id: "MP003",
    nombre: "Zinc bisglicinato",
    lote: "LOT-ZN-2026-012",
    proveedor: "Albion Minerals",
    fechaCaducidad: "2027-01-10",
    fechaRecepcion: "2026-03-10",
    cantidad: 1,
    unidad: "kg",
    coaPendiente: false,
    notas: "",
    fotos: [],
  },
  {
    id: "MP004",
    nombre: "Extracto de alcachofa",
    lote: "LOT-AL-2026-008",
    proveedor: "Herbal Iberia S.L.",
    fechaCaducidad: "2026-09-30",
    fechaRecepcion: "2026-03-05",
    cantidad: 3,
    unidad: "kg",
    coaPendiente: false,
    notas: "",
    fotos: [],
  },
  {
    id: "MP005",
    nombre: "Probioticos L. plantarum",
    lote: "LOT-LP-2026-003",
    proveedor: "BioFerment Labs",
    fechaCaducidad: "2026-08-15",
    fechaRecepcion: "2026-03-12",
    cantidad: 500,
    unidad: "g",
    coaPendiente: false,
    notas: "Conservar 2-8C",
    fotos: [],
  },
];

export const DEMO_FERMENTACIONES: Fermentacion[] = [
  {
    id: "FERM-001",
    producto: "Vital Viver",
    loteProduccion: "VV-2026-003",
    fechaInicio: "2026-03-01",
    materiasPrimas: ["MP001", "MP004", "MP005"],
    controles: [
      { dia: 1, fecha: "2026-03-01", ph: 6.2, temperatura: 21, humedadRelativa: 72, aspectoVisual: "Normal", olor: "Neutro", conforme: true, observaciones: "", fotos: [] },
      { dia: 3, fecha: "2026-03-03", ph: 5.4, temperatura: 22, humedadRelativa: 70, aspectoVisual: "Burbujeo ligero", olor: "Ligeramente acido", conforme: true, observaciones: "Fermentacion iniciada correctamente", fotos: [] },
      { dia: 7, fecha: "2026-03-07", ph: 4.1, temperatura: 21, humedadRelativa: 71, aspectoVisual: "Burbujeo activo", olor: "Acido lactico", conforme: true, observaciones: "pH bajo 4.6 - OK", fotos: [] },
      { dia: 15, fecha: "2026-03-15", ph: 3.8, temperatura: 20, humedadRelativa: 69, aspectoVisual: "Estable", olor: "Acido agradable", conforme: true, observaciones: "", fotos: [] },
      { dia: 30, fecha: "2026-03-30", ph: 3.5, temperatura: 21, humedadRelativa: 70, aspectoVisual: "Clarificado", olor: "Acido suave", conforme: true, observaciones: "", fotos: [] },
    ],
    estado: "activa",
    fotos: [],
    fase: "primaria",
    temperaturaObjetivo: 30,
    duracionDias: 40,
    linea: "liquidos",
    fermentacionPrimariaId: "",
  },
  {
    id: "FERM-002",
    producto: "Digest Viver",
    loteProduccion: "DV-2026-002",
    fechaInicio: "2026-02-20",
    materiasPrimas: ["MP004", "MP005"],
    controles: [
      { dia: 1, fecha: "2026-02-20", ph: 6.0, temperatura: 22, humedadRelativa: 71, aspectoVisual: "Normal", olor: "Neutro", conforme: true, observaciones: "", fotos: [] },
      { dia: 3, fecha: "2026-02-22", ph: 5.1, temperatura: 21, humedadRelativa: 70, aspectoVisual: "Burbujeo", olor: "Acido", conforme: true, observaciones: "", fotos: [] },
      { dia: 7, fecha: "2026-02-26", ph: 4.0, temperatura: 21, humedadRelativa: 72, aspectoVisual: "Activo", olor: "Acido lactico", conforme: true, observaciones: "", fotos: [] },
      { dia: 15, fecha: "2026-03-06", ph: 3.7, temperatura: 20, humedadRelativa: 70, aspectoVisual: "Estable", olor: "Agradable", conforme: true, observaciones: "", fotos: [] },
      { dia: 30, fecha: "2026-03-21", ph: 3.4, temperatura: 21, humedadRelativa: 69, aspectoVisual: "Clarificado", olor: "Suave", conforme: true, observaciones: "", fotos: [] },
      { dia: 40, fecha: "2026-03-31", ph: 3.3, temperatura: 21, humedadRelativa: 70, aspectoVisual: "Terminado", olor: "Suave acido", conforme: true, observaciones: "Fermentacion completada", fotos: [] },
    ],
    estado: "completada",
    fotos: [],
    fase: "primaria",
    temperaturaObjetivo: 30,
    duracionDias: 40,
    linea: "liquidos",
    fermentacionPrimariaId: "",
  },
];

export const DEMO_PRODUCCIONES: HojaProduccion[] = [
  {
    id: "PROD-001",
    loteProduccion: "VV-2026-003",
    producto: "Vital Viver",
    fecha: "2026-03-01",
    operario: "Ana Garcia",
    materiasPrimas: [
      { mpId: "MP001", cantidad: 1.5 },
      { mpId: "MP004", cantidad: 1 },
      { mpId: "MP005", cantidad: 100 },
    ],
    fermentacionId: "FERM-001",
    estado: "en_proceso",
    observaciones: "Lote de produccion marzo",
    fotos: [],
  },
];

export const DEMO_ENVASADOS: HojaEnvasado[] = [
  {
    id: "ENV-001",
    loteEnvasado: "ENV-DV-2026-001",
    loteProduccion: "DV-2026-002",
    producto: "Digest Viver",
    fecha: "2026-04-02",
    operario: "Pedro Lopez",
    formatoEnvase: "vidrio_plastico",
    loteEnvase: "BV-2026-100",
    loteTapon: "TP-2026-050",
    unidades: 120,
    estado: "completado",
    observaciones: "",
    fotos: [],
  },
];

export const DEMO_PRODUCTOS: ProductoStock[] = [
  {
    id: "PROD-VV",
    nombre: "Vital Viver",
    ean: "8412345000001",
    tipo: "liquido",
    categoria: "complemento",
    stock: 85,
    umbralAlerta: 20,
    loteActual: "VV-2026-002",
    materiasPrimas: [
      { nombre: "Extracto cardo mariano", lote: "LOT-CM-2026-001", caducidad: "2027-03-15" },
      { nombre: "Extracto alcachofa", lote: "LOT-AL-2026-008", caducidad: "2026-09-30" },
      { nombre: "Probioticos L. plantarum", lote: "LOT-LP-2026-003", caducidad: "2026-08-15" },
    ],
    envase: "Vidrio 500ml",
    loteEnvase: "BV-2026-088",
    tapon: "Tapon plastico",
    loteTapon: "TP-2026-044",
  },
  {
    id: "PROD-DV",
    nombre: "Digest Viver",
    ean: "8412345000002",
    tipo: "liquido",
    categoria: "complemento",
    stock: 120,
    umbralAlerta: 25,
    loteActual: "DV-2026-002",
    materiasPrimas: [
      { nombre: "Extracto alcachofa", lote: "LOT-AL-2026-008", caducidad: "2026-09-30" },
      { nombre: "Probioticos L. plantarum", lote: "LOT-LP-2026-003", caducidad: "2026-08-15" },
    ],
    envase: "Vidrio 250ml",
    loteEnvase: "BV-2026-089",
    tapon: "Gotero pipeta",
    loteTapon: "GP-2026-011",
  },
  {
    id: "PROD-IV",
    nombre: "Inmuno Viver",
    ean: "8412345000003",
    tipo: "liquido",
    categoria: "complemento",
    stock: 15,
    umbralAlerta: 20,
    loteActual: "IV-2026-001",
    materiasPrimas: [
      { nombre: "Vitamina C", lote: "LOT-VC-2026-045", caducidad: "2026-06-20" },
      { nombre: "Zinc bisglicinato", lote: "LOT-ZN-2026-012", caducidad: "2027-01-10" },
      { nombre: "Probioticos L. plantarum", lote: "LOT-LP-2026-003", caducidad: "2026-08-15" },
    ],
    envase: "HDPE 100ml",
    loteEnvase: "HD-2026-022",
    tapon: "Tapon rosca",
    loteTapon: "TR-2026-015",
  },
  {
    id: "PROD-MV",
    nombre: "Mineral Viver",
    ean: "8412345000004",
    tipo: "solido",
    categoria: "complemento",
    stock: 60,
    umbralAlerta: 15,
    loteActual: "MV-2026-001",
    materiasPrimas: [
      { nombre: "Zinc bisglicinato", lote: "LOT-ZN-2026-012", caducidad: "2027-01-10" },
      { nombre: "Vitamina C", lote: "LOT-VC-2026-045", caducidad: "2026-06-20" },
    ],
    envase: "Vidrio 200g",
    loteEnvase: "BV-2026-090",
    tapon: "Tapon metalico",
    loteTapon: "TM-2026-008",
  },
  {
    id: "PROD-FV",
    nombre: "Flora Viver",
    ean: "8412345000005",
    tipo: "liquido",
    categoria: "alimento",
    stock: 45,
    umbralAlerta: 10,
    loteActual: "FV-2026-001",
    materiasPrimas: [
      { nombre: "Extracto cardo mariano", lote: "LOT-CM-2026-001", caducidad: "2027-03-15" },
      { nombre: "Probioticos L. plantarum", lote: "LOT-LP-2026-003", caducidad: "2026-08-15" },
    ],
    envase: "Vidrio 500ml",
    loteEnvase: "BV-2026-091",
    tapon: "Tapon plastico",
    loteTapon: "TP-2026-045",
  },
  {
    id: "PROD-EV",
    nombre: "Energy Viver",
    ean: "8412345000006",
    tipo: "solido",
    categoria: "alimento",
    stock: 30,
    umbralAlerta: 10,
    loteActual: "EV-2026-001",
    materiasPrimas: [
      { nombre: "Extracto alcachofa", lote: "LOT-AL-2026-008", caducidad: "2026-09-30" },
      { nombre: "Vitamina C", lote: "LOT-VC-2026-045", caducidad: "2026-06-20" },
    ],
    envase: "HDPE 250g",
    loteEnvase: "HD-2026-023",
    tapon: "Tapon rosca",
    loteTapon: "TR-2026-016",
  },
];

export const DEMO_PCCS_COMPLEMENTOS: PCC[] = [
  {
    id: "PCC-C1",
    nombre: "pH fermentacion (dia 7)",
    limiteCritico: "pH <= 4.6",
    frecuencia: "Dia 7 de cada fermentacion",
    responsable: "Responsable produccion",
    tipo: "complemento",
    controles: [
      { id: "CC1-001", pccId: "PCC-C1", fecha: "2026-03-07", valor: "pH 4.1", conforme: true, operario: "Ana Garcia", accionCorrectora: "", fotos: [] },
    ],
  },
  {
    id: "PCC-C2",
    nombre: "Temperatura camara fermentacion",
    limiteCritico: "18-24C",
    frecuencia: "Diaria durante fermentacion",
    responsable: "Responsable produccion",
    tipo: "complemento",
    controles: [],
  },
  {
    id: "PCC-C3",
    nombre: "Control microbiologico producto final",
    limiteCritico: "Ausencia patogenos (RD 3484/2000)",
    frecuencia: "Cada lote",
    responsable: "Laboratorio externo",
    tipo: "complemento",
    controles: [],
  },
  {
    id: "PCC-C4",
    nombre: "Verificacion etiquetado (AESAN)",
    limiteCritico: "Cumplimiento RD 1487/2009",
    frecuencia: "Cada nuevo producto/cambio",
    responsable: "Responsable calidad",
    tipo: "complemento",
    controles: [],
  },
  {
    id: "PCC-C5",
    nombre: "Dosificacion ingredientes activos",
    limiteCritico: "Dentro de rango declarado ±10%",
    frecuencia: "Cada lote produccion",
    responsable: "Operario produccion",
    tipo: "complemento",
    controles: [],
  },
  {
    id: "PCC-C6",
    nombre: "Detector de metales envasado",
    limiteCritico: "Fe 1.5mm, No-Fe 2.0mm, SS 2.5mm",
    frecuencia: "Cada sesion de envasado",
    responsable: "Operario envasado",
    tipo: "complemento",
    controles: [],
  },
];

export const DEMO_PCCS_ALIMENTOS: PCC[] = [
  {
    id: "PCC-A1",
    nombre: "pH fermentacion (dia 7)",
    limiteCritico: "pH <= 4.6",
    frecuencia: "Dia 7 de cada fermentacion",
    responsable: "Responsable produccion",
    tipo: "alimento",
    controles: [],
  },
  {
    id: "PCC-A2",
    nombre: "Temperatura almacenamiento",
    limiteCritico: "< 25C ambiente / < 5C refrigerado",
    frecuencia: "Diaria",
    responsable: "Responsable almacen",
    tipo: "alimento",
    controles: [],
  },
  {
    id: "PCC-A3",
    nombre: "Control alergenos (14 alergenos UE 1169/2011)",
    limiteCritico: "Declaracion completa en etiqueta",
    frecuencia: "Cada producto / cambio formulacion",
    responsable: "Responsable calidad",
    tipo: "alimento",
    controles: [],
  },
  {
    id: "PCC-A4",
    nombre: "Limpieza entre cambios de producto",
    limiteCritico: "Protocolo limpieza completado",
    frecuencia: "Cada cambio de producto",
    responsable: "Operario",
    tipo: "alimento",
    controles: [],
  },
];

export const DEMO_INCIDENCIAS: Incidencia[] = [
  {
    id: "INC-001",
    fecha: "2026-03-20",
    tipo: "Desviacion PCC",
    gravedad: "alta",
    descripcion: "Temperatura camara subio a 26C durante 4 horas por fallo compresor",
    accionCorrectora: "Reparacion compresor. Producto en cuarentena para analisis microbiologico",
    estado: "abierta",
    responsable: "Ana Garcia",
    fotos: [],
  },
  {
    id: "INC-002",
    fecha: "2026-03-15",
    tipo: "Proveedor",
    gravedad: "media",
    descripcion: "COA lote LOT-VC-2026-045 no recibido en plazo",
    accionCorrectora: "Reclamacion al proveedor. Material retenido hasta recepcion COA",
    estado: "abierta",
    responsable: "Pedro Lopez",
    fotos: [],
  },
  {
    id: "INC-003",
    fecha: "2026-03-10",
    tipo: "Envase defectuoso",
    gravedad: "baja",
    descripcion: "3 unidades con tapon mal sellado detectadas en inspeccion visual",
    accionCorrectora: "Unidades retiradas y destruidas. Registro de destruccion firmado",
    estado: "cerrada",
    fechaCierre: "2026-03-11",
    responsable: "Pedro Lopez",
    fotos: [],
  },
];
